### ISSUE TITLE
Trailing Slash is removed

### ISSUE THREAD

**Issue by robjbrain** [spatie/url#19]
This package seems to remove the trailing slash aggressively with no way of avoiding of it?

I discovered this while using Guzzle so i'll give simple example and a real world example of how I encountered it.

```php
$link = 'https://www.domain.com/wp-json/wp/v2/';
$url = Url::fromString($link);

// returns https://www.domain.com/wp-json/wp/v2 
// note the missing trailing slash
echo $url;
```

This caused a problem with guzzle like so:

```php
// This gives an error URI must be a string or UriInterface
$guzzle = new HttpClient([
        'base_uri'  =>  $url
    ]);

// This strips the v2 because guzzle looks for a trailing slash and strips if it doesn't exist
$guzzle = new HttpClient([
        'base_uri'  =>  (string)$url
    ]);

// The url attempted is https://www.domain.com/wp-json/wp/posts
// note the missing "v2"
$guzzle->get('posts');
```

I guess you could say it's an issue with guzzle aggressively removing the last segment. But much of a muchness.

Unfortunately I don't know what to suggest in terms of a solution, at the very least it should be documented that the trailing slash is removed.

**Comment by sebastiandedeyne** [comment]
Hmm I think I blame Guzzle here but I understand the frustration.

I'd accept a non-breaking PR that keeps the trailing slash if it's initially passed. Not sure if this is gonna be easy though.

**Comment by nyamsprod** [comment]
@sebastiandedeyne the question is why is this package removing the trailing slash from the path. it is true that `http://example.com` and `http://example.com/` **may** be considered equal but `http://example.com/v1/` and `http://example.com/v1` can not.  
By removing the trailing slash you are directly feeding wrong information to any package that will use [URL resolution according to RFC3986](https://tools.ietf.org/html/rfc3986#section-5) which is what Guzzle is doing. 
So the only resolution for this bug is to remove the `rtrim` usage in the library. But If I understand it correctly this would mean introducing a BC break.

**Comment by stefanbauer** [comment]
Yeah, 100% agree with @nyamsprod - the `rtrim` should be removed imho, as `http://example.com/sub` and `http://example.com/sub/` are two different but valid locations. I think it doesn't break anything if we just remove the `rtrim`, does it?

**Comment by sebastiandedeyne** [comment]
> the question is why is this package removing the trailing slash from the path

It's been too long. I remember it made some parts of the package easier to have everything consistent, but don't remember where.

I'm willing to review PR that removes `rtrim` and fixes whatever needs to be fixed, but at the moment I don't have time to work on this myself, sorry!

**Comment by stefanbauer** [comment]
Totally get it and understand it. I extended it for now and override this part. Will create a PR that fixes that as soon as I have some time. But dunno when. Thanks for your reply @sebastiandedeyne
